#!/bin/env python3

# TODO some can be generated by setup

appname  = 'orbit'
version  = '0.1'
source   = 'https://github.com/underground-software/orbit'
docs     = 'https://github.com/underground-software/kdlp.underground.software'

# make exernal GET request to find these documents
logo_get    = '/images/kdlp_logo.png'
style_get   = '/style.css'

orbitroot   = '/var/orbit'

# read these documents from a filesystem path
dataroot    = f'{orbitroot}/docs'
# TODO: this will become /var/orbit/databse/orbit.db or something
database    = f'{orbitroot}/orbit.db'

# duration of authentication token validity period
ses_mins    = 180

title       = 'Kernel Development Learning Pipeline'
nav_buttons = [
    (       '/index.md', 'Home'     ),
    ('/course/index.md', 'Course'   ),
    (          '/login', 'Login'    ),
    (       '/register', 'Register' ),
    (      '/dashboard', 'Dashboard'),
    (         '/who.md', 'Who'      ),
    (        '/info.md', 'Info'     ),
    (           '/cgit', 'Git'      )]

sql_verbose = True

production = False
