services:
  orbit:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: orbit
    volumes:
      - ../docs:/orbit/docs
    ports:
      - 80:80
      - 443:443
      - 465:465
      - 995:995
      - 8448:8448
